"""The supervised-span rule, per chat family.

These are the tests that would have caught the port the research prompt suggested:
swapping Qwen's regex markers for gemma's gives a span that swallows the tool RESULT,
because gemma-4 renders a whole tool exchange inside one ``model`` turn. Nothing
downstream notices — the loss falls, the density audit looks healthy — so the rule is
pinned here on synthetic id streams that need no model and no tokenizer files.
"""

from __future__ import annotations

import pytest

from quant_tuner.qat.dialect import (
    DIALECTS,
    Gemma4ChatDialect,
    QwenChatDialect,
    detect,
)

G = Gemma4ChatDialect()

# The exact ids the tokenizer emits, verified against
# google/gemma-4-E4B-it-qat-q4_0-unquantized.
TURN, END, MODEL, USER, SYSTEM, NL = 105, 106, 4368, 2364, 9731, 107
TC_OPEN, TC_CLOSE, TR_OPEN, TR_CLOSE = 48, 49, 50, 51


def _labels(ids: list[int]) -> list[int]:
    return G.labels(ids, "", [], None)


def test_gemma_supervises_model_turn_but_not_its_header() -> None:
    ids = [TURN, MODEL, NL, 700, 701, END, NL]
    assert _labels(ids) == [-100, -100, -100, 700, 701, END, -100]


def test_gemma_terminator_is_a_trained_target() -> None:
    """Dropping the stop token from the mask is what caused the iter-2/3 looping."""
    ids = [TURN, MODEL, NL, 700, END, NL]
    assert _labels(ids)[-2] == END


def test_gemma_never_supervises_user_or_system_turns() -> None:
    ids = [TURN, SYSTEM, NL, 900, END, NL, TURN, USER, NL, 901, END, NL]
    assert _labels(ids) == [-100] * len(ids)


def test_gemma_excludes_the_tool_response_block_inside_a_model_turn() -> None:
    """The whole point. The call is generated by the model; the response is not."""
    ids = [TURN, MODEL, NL,
           TC_OPEN, 800, TC_CLOSE,          # model emits the call -> supervised
           TR_OPEN, 801, 802, TR_CLOSE,     # harness injects the result -> masked
           803,                             # model continues -> supervised
           END, NL]
    assert _labels(ids) == [-100, -100, -100,
                            TC_OPEN, 800, TC_CLOSE,
                            -100, -100, -100, -100,
                            803,
                            END, -100]


def test_gemma_handles_several_tool_rounds_in_one_turn() -> None:
    ids = [TURN, MODEL, NL,
           TC_OPEN, 1, TC_CLOSE, TR_OPEN, 2, TR_CLOSE,
           TC_OPEN, 3, TC_CLOSE, TR_OPEN, 4, TR_CLOSE,
           5, END, NL]
    lab = _labels(ids)
    assert [lab[i] for i in (6, 7, 8, 12, 13, 14)] == [-100] * 6   # both responses
    assert [lab[i] for i in (3, 4, 5, 9, 10, 11, 15, 16)] == [
        TC_OPEN, 1, TC_CLOSE, TC_OPEN, 3, TC_CLOSE, 5, END]


def test_gemma_a_regex_style_span_would_have_included_the_tool_result() -> None:
    """Guards the specific wrong port: 'everything between the header and <turn|>'."""
    ids = [TURN, MODEL, NL, TC_OPEN, TC_CLOSE, TR_OPEN, 42, TR_CLOSE, END, NL]
    lab = _labels(ids)
    naive = ids[3:9]                       # what the regex port would have supervised
    assert 42 in naive and lab[6] == -100


def test_gemma_does_not_run_past_a_missing_terminator() -> None:
    """A truncated render must not leak supervision into the next turn's header."""
    ids = [TURN, MODEL, NL, 700, TURN, USER, NL, 800, END, NL]
    lab = _labels(ids)
    assert lab[3] == 700
    assert lab[4:] == [-100] * 6


def test_qwen_dialect_is_unchanged() -> None:
    """The published corpora's fingerprints depend on this rule byte-for-byte."""
    text = "<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\nyo<|im_end|>\n"
    # (id, char span) pairs standing in for a tokenizer's offset mapping
    toks = [("<|im_start|>", 0, 12), ("user", 12, 16), ("\n", 16, 17), ("hi", 17, 19),
            ("<|im_end|>", 19, 29), ("\n", 29, 30),
            ("<|im_start|>", 30, 42), ("assistant", 42, 51), ("\n", 51, 52),
            ("yo", 52, 54), ("<|im_end|>", 54, 64), ("\n", 64, 65)]
    ids = list(range(len(toks)))
    offs = [(a, b) for _, a, b in toks]
    lab = QwenChatDialect().labels(ids, text, offs, None)
    # only "yo" and the terminating <|im_end|> are supervised
    assert lab == [-100] * 9 + [9, 10, -100]


class _FakeTok:
    def __init__(self, vocab: dict[str, int]) -> None:
        self.v = vocab
        self.inv = {i: s for s, i in vocab.items()}

    def convert_tokens_to_ids(self, s):
        return self.v.get(s, 3)          # gemma/Qwen both return <unk> for a miss

    def convert_ids_to_tokens(self, i):
        return self.inv.get(i, "<unk>")


def test_detect_picks_by_vocabulary_not_by_name() -> None:
    assert detect(_FakeTok({"<turn|>": 106, "<unk>": 3})).name == "gemma4"
    assert detect(_FakeTok({"<|im_end|>": 151645, "<unk>": 3})).name == "qwen"


def test_detect_refuses_an_unknown_family() -> None:
    """A silent wrong-dialect pick would mask the wrong spans everywhere."""
    with pytest.raises(ValueError, match="no known chat dialect"):
        detect(_FakeTok({"<unk>": 3}))


def test_every_registered_dialect_declares_its_stop_piece() -> None:
    for name, d in DIALECTS.items():
        assert d.stop_piece and d.name == name
        assert d.stop_piece in d.control_tokens
